### ISSUE TITLE
Is LAYERCI env var always available?

### ISSUE THREAD

**Issue by emanuelb** [layer-devops/docs#29]
> `LAYERCI` is always true in LayerCI test runs.

is test run a different kind of run? what different types of runs are available?
how is it possible to detect LayerCI by looking at environment variables?
The below used env vars:
`CI=true, IS_CI_MACHINE=true, CI_MACHINE=true, IN_CI_MACHINE=true, IN_CI=true`
are not specific var names (can be used in other tool)
See related issue: https://github.com/watson/ci-info/issues/63 (would be great if you can comment on it as well)

**Comment by ColinChartier** [comment]
Yes, those variables are always true in our CI runs.
